spring:
  main:
    log-startup-info: false
    banner-mode: off
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate
    h2:
      console:
        enabled: true
    username: sa
    password: password
    driverClassName: org.h2.Driver
logging.level.org:
  zalando:
    logbook: INFO