CREATE TABLE IF NOT EXISTS rating (
    rating_id INT PRIMARY KEY,
    rating VARCHAR
              );

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    description VARCHAR,
    release_date DATE,
    duration INT,
    rating_id INT REFERENCES rating
              );

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR,
    login VARCHAR,
    name VARCHAR,
    birthday DATE
              );

CREATE TABLE IF NOT EXISTS users_liked (
    film_id BIGINT REFERENCES films ON DELETE CASCADE,
    user_id BIGINT REFERENCES users ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
              );

CREATE TABLE IF NOT EXISTS friends (
    user_id BIGINT REFERENCES users ON DELETE CASCADE,
    friend_id BIGINT REFERENCES users ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
              );

CREATE TABLE IF NOT EXISTS genres (
    genre_id INT PRIMARY KEY,
    genre VARCHAR
              );

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT,
    genre_id INT REFERENCES genres,
    PRIMARY KEY (film_id, genre_id)
              );

CREATE TABLE IF NOT EXISTS directors (
    director_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_directors (
    film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE,
    director_id INT REFERENCES directors(director_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
    );